QuoteFinder/urls.py
from django.contrib import admin
from django.urls import path, include
from search.views import homepage,searchresult
from about.views import about
from authors.views import allauthors
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name="homepage"),
    path('search/', searchresult, name="searchresult"),
    path('authors/', include('authors.urls')),
    path('topics/', include('topics.urls')),
    path('about/', about, name="about"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authors/urls.py
from django.urls import path
from . import views

app_name = "authors"

urlpatterns = [

    path('', views.allauthors, name="allauthors"),
    path('<str:key>/', views.detailauthor, name="detailauthor"),
    path('<str:name>/allquotes', views.allauthorquotes, name="allauthorquotes"),
]

topics/urls.py
from django.urls import path
from . import views

app_name = "topics"

urlpatterns = [

    path('', views.alltopics, name="alltopics"),
    path('<str:topic>/', views.detail, name="detail"),
]

about/models.py
from django.db import models

# Create your models here.

authors/models.py
from django.db import models

# Create your models here.
class Authors(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=5000)
    birth_date = models.DateField()
    death_date = models.DateField(null=True, blank=True)
    image = models.ImageField(upload_to="authors/images/")

    def __str__(self):
        return self.name

search/models.py
from django.db import models

# Create your models here.
class Quotes(models.Model):
    phrase = models.TextField(max_length=5000)
    author = models.CharField(max_length=200)
    source = models.CharField(max_length=500)
    topics = models.CharField(max_length=500)

    def __str__(self):
        return str(self.id)

about/views.py
from django.shortcuts import render

# Create your views here.
def about(request):
    return render(request, "about/about.html")

authors/views.py
from django.shortcuts import render
from .models import Authors
from search.models import Quotes

# Create your views here.
def allauthors(request):
    authors = Authors.objects.all().order_by('-name')
    authorstable = {}
    for author in authors:
        authorstable[author.name] = Quotes.objects.filter(author=author.name).count()
    return render(request,"authors/allauthors.html",{"authorstable":authorstable})

def detailauthor(request, key):
    authors = Authors.objects.filter(name=key)
    return render(request, "authors/detailauthor.html", {'authors': authors})

def allauthorquotes(request, name):
    quotes = Quotes.objects.filter(author=name)
    return render(request, "authors/allauthorquotes.html", {'quotes': quotes})

search/views.py
from django.shortcuts import render
from .models import Quotes

# Create your views here.

def homepage(request):
    return render(request,"search/homepage.html")

def searchresult(request):
    query = request.GET.get('q')
    results = Quotes.objects.filter(phrase__contains=query)
    return render(request, "search/searchresult.html", {'results': results, 'error':"there is no quotes."})

topics/views.py
from django.shortcuts import render, get_object_or_404
from search.models import Quotes


# Create your views here.
def alltopics(request):
    topics = ["life", "love", "war"]
    return render(request, "topics/alltopics.html", {"topics": topics})

def detail(request, topic):
    results = Quotes.objects.filter(topics__contains=topic)
    print(results)
    return render(request, "topics/detail.html", {"results": results})

about/templates/about/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
    <h1>About Us</h1>
    <h2>We're here to chew gum and developp, and we're already out of bubblegum.</h2>
</body>
</html>

authors/templates/authors/allauthorquotes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All Quotes</title>
</head>
<body>
    <table>
  <tr>
    <th>Quote</th>
    <th>Author</th>
    <th>Source</th>
    <th>Topics</th>
  </tr>
     {% for quote in quotes %}
      <tr>
        <td>{{ quote.phrase }} </td>
        <td>{{ quote.author }} </td>
        <td>{{ quote.source }} </td>
        <td>{{ quote.topics }} </td>
      </tr>
    {% endfor %}
</table>
</body>
</html>

authors/templates/authors/allauthors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Authors</title>
</head>
<body>
    <h1>Authors</h1>
    <table>
      <tr>
        <th>Name</th>
        <th>Number of quotes</th>
      </tr>
        {% for key,value in authorstable.items %}
          <tr>

            <td><a href="{% url 'authors:detailauthor' key %}">{{ key }}</a> </td>
            <td>{{ value }} </td>

          </tr>
        {% endfor %}

</table>
</body>
</html>

authors/templates/authors/detailauthor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Author</title>
</head>
<body>
    {% for author in authors %}
        <img src="{{ author.image.url }}" class="img-fluid mb-2" height="100" width="100">
        <p>Name : {{ author.name }} </p>
        <p>Description : {{ author.description }} </p>
        <p>Date of Birth : {{ author.birth_date }} </p>
        <p>Date of Death : {{ author.death_date }} </p>
        <form action="{% url 'authors:allauthorquotes' author.name %}">
        <input type="submit" value="All Quotes" />
        </form>
    {% endfor %}

</body>
</html>

search/templates/search/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Quote Finder</title>
    <link rel="stylesheet" href="static/search/homepage.css">
</head>
<body>

    <div class="topnav">
      <a class="active" href="{% url 'homepage' %}">Home</a>
      <a href="{% url 'authors:allauthors' %}">Authors</a>
      <a href="{% url 'topics:alltopics' %}">Topics</a>
      <a href="{% url 'about' %}">About</a>
    </div>

    <form method='GET' action="{% url 'searchresult' %}">
        <div class="wrap">
           <div class="search">
              <input type="text" class="searchTerm" name="q" placeholder="Looking for a Quote?">
              <button type="submit" class="searchButton">
                <i class="fa fa-search"></i>
             </button>
           </div>
        </div>
    </form>
</body>
</html>

search/templates/search/searchresult.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Result</title>
</head>
<body>
<table>
    {% if not results %}
        {{ error }}
    {% else %}
  <tr>
    <th>Quote</th>
    <th>Author</th>
    <th>Source</th>
    <th>Topics</th>
  </tr>
     {% for result in results %}
      <tr>
        <td>{{ result.phrase }} </td>
        <td>{{ result.author }} </td>
        <td>{{ result.source }} </td>
        <td>{{ result.topics }} </td>
      </tr>
    {% endfor %}
    {% endif %}
</table>

</body>
</html>

topics/templates/topics/alltopics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topics</title>
</head>
<body>
    {% for topic in topics %}
    <a href="{% url 'topics:detail' topic %}">{{ topic }}</a>
    {% endfor %}
</body>
</html>

topics/templates/topics/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topic</title>
</head>
<body>
    {{ topic }}
    <table>

      <tr>
        <th>Quote</th>
        <th>Author</th>
        <th>Source</th>
        <th>Topics</th>
      </tr>
         {% for result in results %}
          <tr>
            <td>{{ result.phrase }} </td>
            <td>{{ result.author }} </td>
            <td>{{ result.source }} </td>
            <td>{{ result.topics }} </td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>